CREATE TABLE `USERS` (
  `LOGIN` varchar(128) PRIMARY KEY,
  `PASSWORD` varchar(128) NOT NULL,
  `EMAIL` varchar(128),
  `TYPE` varchar(128) NOT NULL,
  `ORGANIZATION` varchar(128) NOT NULL,
  `SALT` varchar(128) NOT NULL,
  `CREDITS` integer,
  `LATEST_UPDATE` date
);

CREATE TABLE `REFRESH_TOKENS` (
  `LOGIN` varchar(128) PRIMARY KEY,
  `TOKEN` varchar(128),
  `EXPIRY` date
);

CREATE TABLE `OFFERS` (
  `OFFER_ID` integer PRIMARY KEY,
  `NAME` varchar(255) NOT NULL,
  `PRICE` integer NOT NULL,
  `ORGANIZATION` varchar(255) NOT NULL,
  `CATEGORY` varchar(128) NULL
);

CREATE TABLE `CATEGORIES` (
	NAME varchar(128) PRIMARY KEY
);

CREATE TABLE `ORGANIZATIONS` (
  `NAME` varchar(255) PRIMARY KEY,
  `TYPE` varchar(128) NOT NULL
);

CREATE TABLE `DISCOUNTS` (
  `DISC_ID` integer PRIMARY KEY,
  `OFFER_ID` integer NOT NULL,
  `NAME` varchar(255),
  `REDUCTION` varchar(255) NOT NULL
);

CREATE TABLE `CODES` (
  `CODE_ID` integer PRIMARY KEY,
  `OFFER_ID` integer NOT NULL,
  `EXPIRY` date NOT NULL
);

CREATE TABLE `TRANSACTIONS` (
  `TRANS_ID` integer PRIMARY KEY AUTO_INCREMENT,
  `LOGIN` varchar(128) NOT NULL,
  `TRANS_DATE` date NOT NULL,
  `CODE_ID` integer NOT NULL,
  `PRICE` integer NOT NULL,
  `SHOP` varchar(255) NOT NULL
);

CREATE TABLE `CONTACT_INFO` (
  `NAME` varchar(128),
  `POSITION` varchar(128),
  `EMAIL` varchar(128) NOT NULL,
  `PHONE` varchar(128) NOT NULL
);

CREATE TABLE `CONTACT_REQUESTS` (
  `CONT_REQ_ID` integer PRIMARY KEY AUTO_INCREMENT,
  `CONT_REQ_DATE` date NOT NULL,
  `SUBJECT` varchar(64) NOT NULL,
  `BODY` varchar(1024) NOT NULL
);

ALTER TABLE `REFRESH_TOKENS` ADD FOREIGN KEY (`LOGIN`) REFERENCES `USERS` (`LOGIN`);

ALTER TABLE `DISCOUNTS` ADD FOREIGN KEY (`OFFER_ID`) REFERENCES `OFFERS` (`OFFER_ID`);

ALTER TABLE `CODES` ADD FOREIGN KEY (`OFFER_ID`) REFERENCES `OFFERS` (`OFFER_ID`);

ALTER TABLE `TRANSACTIONS` ADD FOREIGN KEY (`CODE_ID`) REFERENCES `CODES` (`CODE_ID`);

ALTER TABLE `TRANSACTIONS` ADD FOREIGN KEY (`LOGIN`) REFERENCES `USERS` (`LOGIN`);

ALTER TABLE `OFFERS` ADD FOREIGN KEY (`ORGANIZATION`) REFERENCES `ORGANIZATIONS` (`NAME`);

ALTER TABLE `USERS` ADD FOREIGN KEY (`ORGANIZATION`) REFERENCES `ORGANIZATIONS` (`NAME`);

ALTER TABLE `TRANSACTIONS` ADD FOREIGN KEY (`SHOP`) REFERENCES `ORGANIZATIONS` (`NAME`);

ALTER TABLE `OFFERS` ADD FOREIGN KEY (`CATEGORY`) REFERENCES `CATEGORIES` (`NAME`);

INSERT INTO ORGANIZATIONS VALUES ('Swagger', 'Swagger');
INSERT INTO USERS VALUES ('Swagger', '11CE1EC601DF94DBE9670B26A13A0B84C8D5CEBC39E772536F9659EA1E1BB7366704BE2C9D0CC62DBBAD72B8C851BA580ACD98C6D37A511045F0708CF8891ECE', 'test@gmail.com', 'Administrator', 'Swagger', '4EB39F1500E1C7BFA6B56F03E327779B318282D2F2AFE339E6DB0647E9F463C0D2231E93601FBFB1524629E74A852D1158792F7981C501853045AB3F44D1D59B', NULL, NULL);
INSERT INTO REFRESH_TOKENS (Login) VALUES ('Swagger');

COMMIT;
