CREATE DATABASE LojShopDB;

CREATE TABLE `OFFERS` (
  `OFFER_ID` integer PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `PRICE` integer NOT NULL,
  `ORGANIZATION` varchar(255) NOT NULL,
  `STATE` bit DEFAULT true,
  `CATEGORY` varchar(128)
);

CREATE TABLE `ORGANIZATIONS` (
  `NAME` varchar(255) PRIMARY KEY
);

CREATE TABLE `DISCOUNTS` (
  `DISC_ID` integer PRIMARY KEY AUTO_INCREMENT,
  `OFFER_ID` integer NOT NULL,
  `NAME` varchar(255),
  `REDUCTION` varchar(255) NOT NULL,
  `EXPIRY` timestamp NOT NULL
);

CREATE TABLE `CODES` (
  `CODE_ID` integer PRIMARY KEY,
  `OFFER_ID` integer NOT NULL,
  `STATE` bit DEFAULT true,
  `EXPIRY` timestamp NOT NULL
);

CREATE TABLE `CATEGORIES` (
  `NAME` varchar(128) PRIMARY KEY
);

ALTER TABLE `OFFERS` ADD FOREIGN KEY (`ORGANIZATION`) REFERENCES `ORGANIZATIONS` (`NAME`);

ALTER TABLE `DISCOUNTS` ADD FOREIGN KEY (`OFFER_ID`) REFERENCES `OFFERS` (`OFFER_ID`);

ALTER TABLE `CODES` ADD FOREIGN KEY (`OFFER_ID`) REFERENCES `OFFERS` (`OFFER_ID`);

ALTER TABLE `OFFERS` ADD FOREIGN KEY (`CATEGORY`) REFERENCES `CATEGORIES` (`NAME`);

COMMIT;