services:
  mysql:
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db_user_pass
    image: "mysql:latest"
    networks:
      - loj-backend-network
    volumes:
      - db-data:/var/lib/mysql
      - ../Scripts:/docker-entrypoint-initdb.d